services:
  model-service:
    gpus: all
    environment:
      DOC_LINKER_EMBEDDING_DEVICE: ${DOC_LINKER_EMBEDDING_DEVICE:-cuda:0}
      DOC_LINKER_EMBEDDING_USE_FP16: ${DOC_LINKER_EMBEDDING_USE_FP16:-true}
      DOC_LINKER_RERANKER_DEVICE: ${DOC_LINKER_RERANKER_DEVICE:-cuda:0}
      DOC_LINKER_RERANKER_USE_FP16: ${DOC_LINKER_RERANKER_USE_FP16:-true}

  model-cache:
    gpus: all
    environment:
      DOC_LINKER_EMBEDDING_DEVICE: ${DOC_LINKER_EMBEDDING_DEVICE:-cuda:0}
      DOC_LINKER_EMBEDDING_USE_FP16: ${DOC_LINKER_EMBEDDING_USE_FP16:-true}
      DOC_LINKER_RERANKER_DEVICE: ${DOC_LINKER_RERANKER_DEVICE:-cuda:0}
      DOC_LINKER_RERANKER_USE_FP16: ${DOC_LINKER_RERANKER_USE_FP16:-true}
